In [2]:
 import numpy as np

In [3]:
# 1.creating arrays

In [4]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [5]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [6]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [11]:
arr = [1,2,3]
arr1 = [4,5,6]
arr2 = np.array([arr,arr1])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
arr = [1,2,3]
arr1 = [4,5,6]
arr3 = [7,8,9]
arr2 = np.array([[arr,arr1,arr3]])
print(arr2)
print(arr2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [12]:
# 3.numpy array attributes

In [20]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)
print(arr1.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
6


In [22]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[1 2 3]
1
3
(3,)
int32


In [27]:
arr1 = np.array([[[1,2,3],[11,22,33],[44,34,66]]])
print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[[ 1  2  3]
  [11 22 33]
  [44 34 66]]]
3
9
(1, 3, 3)
int32


In [28]:
# 3. array initialization methods

In [30]:
# zero array

arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
 #one array
arr = np.ones((1,3))
print(arr)

[[1. 1. 1.]]


In [34]:
# full array
arr = np.full((3,2),7)
print(arr)

[[7 7]
 [7 7]
 [7 7]]


In [35]:
# identity metrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# iempty array
print(np.empty(2))

[1.63777334e-307 9.83366805e-308]


In [45]:
# evenly spaced array
print(np.arange(1,4,2))
print(np.arange(1,4,1))
print(np.arange(1,3,1))

[1 3]
[1 2 3]
[1 2]


In [48]:
# specific values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [51]:
# random values array -- float
arr = np.random.rand(3,2)
print(arr)

[[0.53080028 0.29673441]
 [0.73094222 0.19315647]
 [0.619925   0.30856684]]


In [56]:
# random values array -- int
arr = np.random.randint(1,100,(3,3))
print(arr)

[[38 55  3]
 [99  1 60]
 [98 94 82]]


In [ ]:
# ARRA INDEXING and slicing

In [57]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [61]:
# indexing
print(a[0])
print(a[4])
print(a[-1])

1
9
[3 5 7]
9


In [66]:
#slicing
print(a[1:4:1])
print(a[1:7:2])
print(a[1:4])

[3 5 7]
[3 7]
[3 5 7]


In [67]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [77]:
print(arr1[0][0]  )
print(arr1[1][0]  )

1
4


In [81]:
print(arr1[1:]  )
print(arr1[0:]  )

[[4 5 6]]
[[1 2 3]
 [4 5 6]]


In [82]:
print(arr1[:,0]  )

[1 4]


In [96]:
arr = ([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[2][2])
print(arr[1][2])
print(arr[:2])
print(arr[2:])
 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
6
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9]]


In [97]:
# array reshaping and flattenung

In [98]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [100]:
reshape = arr.reshape((6,1))
print(reshape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [101]:
reshape1 = arr.reshape((2,3))
print(reshape1)

[[1 2 3]
 [4 5 6]]


In [102]:
print(reshape1.flatten())

[1 2 3 4 5 6]


In [103]:
# array stacking and splitting

In [105]:
a =  np.array([1,2,3])
b =  np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [106]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [109]:
print(np.hsplit(c,3))
print(np.vsplit(c,2))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [110]:
# methematical oprations on array

In [111]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [113]:
print(a+10)
print(a-30)
print(a*2)


[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]


In [115]:
print(np.square(a))

[ 100  400 1600  900]


In [116]:
# methematical oprations on muliple array

In [118]:
a = np.array([1,2,4])
b = np.array([5,6,7])
print(a)
print(b)

[1 2 4]
[5 6 7]


In [122]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[ 6  8 11]
[-4 -4 -3]
[ 5 12 28]
[0.2        0.33333333 0.57142857]


In [123]:
print(np.dot(a,b))

45


In [127]:
print(a.T)

[1 2 4]


In [130]:
t = np.array([[1,2,3],[4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [131]:
# statistical function

In [132]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [137]:
print(np.sum(a))
print(np.median(a))
print(np.min(a))
print(np.std(a))

21
3.5
1
1.707825127659933


In [138]:
# array comparison

In [139]:
a = np.array([1,2,4])
b = np.array([5,6,7])
print(a)
print(b)

[1 2 4]
[5 6 7]


In [142]:
print(a==b)
print(np.array_equal(a,b))

[False False False]
False


In [143]:
# broadcasting

In [145]:
a = np.array([1,2,4])
b = np.array([5])
print(a+b)

[6 7 9]


In [146]:
# hanndling with nan

In [147]:
data = np.array([1,2,np.nan, 4, np.inf])
print(data)

[ 1.  2. nan  4. inf]


In [148]:
print(np.isnan(data))

[False False  True False False]


In [149]:
print(np.nan_to_num(data))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [150]:
# save and load array

In [152]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [154]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]
