In [1]:
import numpy as np 

In [2]:
arr1 = np.zeros(5) # one dimenstion -size -5
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)
print(arr1)

5
1
float64
(5,)
[0. 0. 0. 0. 0.]


In [5]:
arr2 = np.zeros([2,3]) # (fist dimenstion element second dimenstion element)
#[
#    [0 0 0]
 #   [0 0 0]
#]
print(arr2)
print(arr2.size)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)



[[0. 0. 0.]
 [0. 0. 0.]]
6
(2, 3)
2
float64


In [6]:
arr3 = np.zeros([3,3,4])
print(arr3)
print(arr3.size)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
36
(3, 3, 4)
float64
3


In [10]:
arr1 = np.ones(5)
print(arr1)
arr2 = np.ones([2,3])
print(arr2)
arr3 = np.ones([3,4,5])
print(arr3)
print(arr3.size)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
60
(3, 4, 5)
float64
3


In [11]:
# full array
arr1 = np.full(2,6) #fist = no number element ,secoend = value
arr2 = np.full(4,10)
arr3 = np.full(7,89)
print(arr1)
print(arr2)
print(arr3)

[6 6]
[10 10 10 10]
[89 89 89 89 89 89 89]


In [13]:
# arange()array-- makes a 1-d arry of specifies range
arr1 = np.arange(1,10)
arr2 = np.arange(1,51,2)
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [15]:
#identity matrix
arr1 = np.eye(5)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
"""create an array from number 40 - 132
create an 4-d array of zeros 
create an 2-d array of 1's
cteate an array where the number 213 isrepeated 12 times 
create an array where the number 1.001 is repeated 8 times 
create an identity matrix of shape (4,4)
create an identity matrix of shape (9,9)
"""

In [19]:
arr1 = np.arange(40, 133)
print(arr1)
 
arr1 = np.zeros((2, 2, 2, 2))
print(arr1)

arr1 = np.ones([2,2,])
print(arr1)
 
arr1 = np.full(12, 213)
print(arr1)
 
arr1 = np.full(8, 1.001)
print(arr1)
 
arr1 = np.eye(4)
print(arr1)
 
arr1 = np.eye(9)
print(arr1)

[ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132]
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[1. 1.]
 [1. 1.]]
[213 213 213 213 213 213 213 213 213 213 213 213]
[1.001 1.001 1.001 1.001 1.001 1.001 1.001 1.001]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
# aggregate function
arr1 = np.arange(30,45)
print(arr1)
print(sum(arr1))
print(min(arr1))
print(max(arr1))
print(arr1.std()) # standard deviation
print(arr1.var()) # variance
print(arr1.argmax()) # argument maximum
print(arr1.argmin()) # argument mimimum
print(arr1.mean()) # avgrage

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
555
30
44
4.320493798938574
18.666666666666668
14
0
37.0


In [26]:
arr1 = np.arange(2,10,15,-1,-9,5,45,100)
print(arr1)

<class 'TypeError'>: arange() takes from 0 to 4 positional arguments but 8 were given

In [ ]:
#max dimenstions you can create 64in 2.X var

In [2]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

(3,)
3
1
int32


In [7]:
arr1 = np.array([[1,2,3] ,[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int32


In [10]:
arr1 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)
9
3
int32


In [15]:
arr1 = np.array(65)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

65
()
1
0
int32


In [17]:
arr1 = np.array([1,2,3,4,5] , ndmin = 5)
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
5
5
int32


In [23]:
arr1 = np.array([[20,30,100],[30,50,60]])
print(arr1)
print(sum(arr1))
print(min(arr1))
print(max(arr1))
print(arr1.std()) # standard deviation
print(arr1.var()) # variance
print(arr1.argmax()) # argument maximum
print(arr1.argmin()) # argument mimimum
print(arr1.mean()) # avgrage

[[ 20  30 100]
 [ 30  50  60]]
[ 50  80 160]


<class 'ValueError'>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()